# Generated by Django 6.0.2.dev20260204161912 on 2026-02-11 18:25

import django_mongodb_backend.fields
import medical_records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_type', models.CharField(max_length=50)),
                ('cc_number', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.BigIntegerField()),
                ('patient_record', django_mongodb_backend.fields.EmbeddedModelField(embedded_model=medical_records.models.PatientRecord)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', django_mongodb_backend.fields.EncryptedCharField(max_length=11)),
                ('billing', django_mongodb_backend.fields.EncryptedEmbeddedModelField(embedded_model=medical_records.models.Billing)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
